[user]
name = 'Drew Olson'
email = 'drew@drewolson.org'

[ui]
default-command = 'log'

[aliases]
pr-fetch = ['util', 'exec', '--', 'bash', '-c', '''
set -euo pipefail
git fetch $1 pull/$2/head:pr/$2
jj new pr/$2
''', '']

[revsets]
bookmark-advance-to = 'latest(::@ & ~empty())'
