export CLICOLOR=1
export EDITOR='vim'
export ERL_AFLAGS="-kernel shell_history enabled"
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_DEFAULT_OPTS='--reverse'
export GO111MODULE="on"
export GOPATH=$HOME/go
export GOPROXY="https://proxy.golang.org"
export GPG_TTY=$(tty)
export HOMEBREW_NO_ANALYTICS=1
export KERL_BUILD_DOCS=yes
export KERL_DOC_TARGETS=chunks
export LSCOLORS=ExFxCxDxBxegedabagacad
export NEXT_TELEMETRY_DISABLED=1
